// <auto-generated />
namespace ContextTests.Dal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_assignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_assignment));
        
        string IMigrationMetadata.Id
        {
            get { return "201310131757528_Add_assignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
