// <auto-generated />
namespace ContextTests.Dal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Student_extended : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_extended));
        
        string IMigrationMetadata.Id
        {
            get { return "201403161909094_Student_extended"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
