<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(Floor2PlanRoot)Test\UnitTest\UnitTest.Build.props" />
  <ItemGroup>
    <PackageReference Include="Akka.Hosting.TestKit" />
    <PackageReference Include="Akka.TestKit" />
    <PackageReference Include="Refit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Core\Src\Contracts\Contracts.Infrastructure.Connectors\Contracts.Infrastructure.Connectors.csproj" />
    <ProjectReference Include="..\..\Modules\Core\Src\Contracts\Contracts.Model\Contracts.Model.csproj" />
    <ProjectReference Include="..\..\Modules\Core\Src\Domain\Domain.Model\Domain.Model.csproj" />
    <ProjectReference Include="..\..\Src\Infrastructure.Akka.Contracts\Infrastructure.Akka.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\Core\Test\Utility\Floor2Plan.TestUtility.Common\Floor2Plan.TestUtility.Common.csproj" />
    <ProjectReference Include="..\..\Src\Floor2Plan.Connectors.P6\Floor2Plan.Connectors.P6.csproj" />
    <ProjectReference Include="..\..\Modules\Core\Src\Infrastructure\Infrastructure.Process.Contracts\Infrastructure.Process.Contracts.csproj" />
  </ItemGroup>
</Project>
