// <auto-generated />
using System;
using HourApprovals.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HourApprovals.Data.Migrations.Migrations
{
    [DbContext(typeof(HourApprovalsDbContext))]
    partial class HourApprovalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hour_approvals")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HourApprovals.Infrastructure.Persistence.Entities.ActiveTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("HoursToGo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActiveForCurrentUser")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("PlannedFinish")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date");

                    b.Property<decimal>("Progress")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("WorkedHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("active_tasks", "hour_approvals");
                });

            modelBuilder.Entity("HourApprovals.Infrastructure.Persistence.Entities.ApprovalRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ApprovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("HoursToGo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly?>("PlannedFinish")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date");

                    b.Property<decimal>("Progress")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WorkedHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "ApprovedAtUtc");

                    b.ToTable("approval_records", "hour_approvals");
                });

            modelBuilder.Entity("HourApprovals.Infrastructure.Persistence.Entities.ApprovalRecordEntity", b =>
                {
                    b.HasOne("HourApprovals.Infrastructure.Persistence.Entities.ActiveTaskEntity", "Task")
                        .WithMany("ApprovalRecords")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HourApprovals.Infrastructure.Persistence.Entities.ActiveTaskEntity", b =>
                {
                    b.Navigation("ApprovalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
