<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Akka.TestKit" />
    <PackageReference Include="Akka.TestKit.Xunit" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>
  <Import Project="..\..\..\build\Platform.Logging.Tests.props" />
</Project>
