<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AkkaTeach.Worker-79dbc537-5509-4f84-9b50-a431b64ddb3a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Hosting" Version="1.5.71" />
    <PackageReference Include="Akka.Logger.Serilog" Version="1.5.69" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.18.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AkkaTeach.Core\AkkaTeach.Core.csproj" />
  </ItemGroup>
</Project>
