// <auto-generated />
namespace Datalayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Modules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modules));
        
        string IMigrationMetadata.Id
        {
            get { return "201308221823491_Modules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
