// <auto-generated />
using System;
using ApiImportActorPoc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiImportActorPoc.Data.Migrations.Migrations
{
    [DbContext(typeof(ImportDbContext))]
    [Migration("20260612170813_AddEntityExternalIds")]
    partial class AddEntityExternalIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ActivityRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceActivityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetActivityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceActivityId");

                    b.HasIndex("TargetActivityId");

                    b.ToTable("ActivityRelations", (string)null);
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.AssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ComponentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentComponentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentComponentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.EntityExternalIdEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InternalEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InternalEntityId");

                    b.HasIndex("System", "Value")
                        .IsUnique();

                    b.ToTable("EntityExternalIds", (string)null);
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ActivityEntity", b =>
                {
                    b.HasOne("ApiImportActorPoc.Data.Entities.ComponentEntity", "Component")
                        .WithMany("Activities")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ActivityRelationEntity", b =>
                {
                    b.HasOne("ApiImportActorPoc.Data.Entities.ActivityEntity", "SourceActivity")
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("SourceActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiImportActorPoc.Data.Entities.ActivityEntity", "TargetActivity")
                        .WithMany()
                        .HasForeignKey("TargetActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceActivity");

                    b.Navigation("TargetActivity");
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.AssignmentEntity", b =>
                {
                    b.HasOne("ApiImportActorPoc.Data.Entities.ActivityEntity", "Activity")
                        .WithMany("Assignments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ComponentEntity", b =>
                {
                    b.HasOne("ApiImportActorPoc.Data.Entities.ComponentEntity", "ParentComponent")
                        .WithMany("ChildComponents")
                        .HasForeignKey("ParentComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApiImportActorPoc.Data.Entities.ProjectEntity", "Project")
                        .WithMany("Components")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComponent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ActivityEntity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("OutgoingRelations");
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ComponentEntity", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ChildComponents");
                });

            modelBuilder.Entity("ApiImportActorPoc.Data.Entities.ProjectEntity", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
